### ISSUE TITLE
[!] Twitter error: [{u'message': u'Invalid or expired token.', u'code': 89}] 

### ISSUE THREAD

**Issue by BaraSec** [x0rz/tweets_analyzer#1]
Hi, how are you ?
I am using your script and I get this error after executing this command: 
"python2 tweets_analyzer.py -n someUSERNAME".

The error is: 
[!] Twitter error: [{u'message': u'Invalid or expired token.', u'code': 89}].

how to overcome this issue ?

Thanks in advance.

**Comment by x0rz** [comment]
Have you changed the `secrets.py` file?
You have to get your own API key at https://dev.twitter.com/

**Comment by BaraSec** [comment]
Oh I think this error occurs because I missed the "update the keys at secrets.py" file.

Thanks anyway!

**Comment by BaraSec** [comment]
@x0rz Thanks. Yes I missed that step, sorry for the inappropriate issue.
