### ISSUE TITLE
"Looks like we do not have enough tweets from user", average daily post # off?

### ISSUE THREAD

**Issue by packetrat** [x0rz/tweets_analyzer#11]
I get this error, suggesting I use --limit, and the average given for daily posts looks to be roughly double what it should be.

**Comment by x0rz** [comment]
Could you give me the screen_name that does this so I can reproduce? 
Thank you 👍

**Comment by packetrat** [comment]
disregard my last - it's simply that the sample size is so large that even expanding the limit was giving sub-day sized data chunks.
