### ISSUE TITLE
[!] Twitter error: [{'message': 'Invalid or expired token.', 'code': 89}]

### ISSUE THREAD

**Issue by elharezmi** [x0rz/tweets_analyzer#12]
My python version 3.5.2 commands
  $ python tweets_analyzer.py -n @screename --friends  
[+] Getting @screenname account data...
[!] Twitter error: [{'message': 'Invalid or expired token.', 'code': 89}]

**Comment by Machou** [comment]
You need create an application on https://apps.twitter.com/ and edit secrets.py

**Comment by stasfilin** [comment]
Hi @elharezmi 

- Go to https://apps.twitter.com/
- Create new app
- Go to **Keys and Access Tokens**
- Click **Regenerate Consumer Key and Secret**
- Click **Regenerate My Access Token and Token Secret**
- Now you have Consumer Key (API Key), Consumer Secret (API Secret), Access Token, Access Token Secret

Best Regards,
Stanislav

**Comment by elharezmi** [comment]
Thank you :+1:
