### ISSUE TITLE
Retirer les xxxxx de secrets.py

### ISSUE THREAD

**Issue by Machou** [x0rz/tweets_analyzer#14]
Possible de retirer les xxxx de secrets.py ?

C'est un peu "relou" lorsque l'on doit renseigner ses clés :P

**Comment by x0rz** [comment]
En fait les "xxxx" paraissent utiles quand tu vois le nombre de personnes ne sachant pas remplacer les clefs API (manque presque une flèche en ASCII art).
Vu que c'est une action que tu ne fais qu'une seule fois, c'est finalement peu cher payé.
