### ISSUE TITLE
Python versions and SSL/TLS

### ISSUE THREAD

**Issue by kflanagan** [x0rz/tweets_analyzer#20]
I have found that I got errors 
Python 3.x is required unless you deal with these two warnings.
SNIMissingWarning  -- https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

InsecurePlatformWarning -- https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings 

This is on a fully updated Linux Mint system.
Precision-WorkStation-390 ~ # uname -a
Linux Precision-WorkStation-390 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Precision-WorkStation-390 ~ # python --version
Python 2.7.6

**Comment by kflanagan** [comment]
A clean installation of the 3.x python branch on Windows 10 worked well, right away.

**Comment by packetrat** [comment]
I'll make a note of it. MacOS is not a fan , at least as written.

Sean Gallagher
IT Editor
Ars Technica
@thepacketrat
312 281 5123

On Feb 6, 2017, at 8:22 PM, Kevin Flanagan <notifications@github.com<mailto:notifications@github.com>> wrote:


A clean installation of the 3.x python branch on Windows 10 worked well, right away.

**Comment by x0rz** [comment]
This is a known _Tweepy_ issue:
 - https://bottomdrawerprojects.blogspot.fr/2016/02/tweeting-from-your-pi-fixing-issues.html
 - https://stackoverflow.com/questions/39578195/tweepy-resolved-ssl-insecureplatform-error-but-tweet-fails

Won't fix it here
