### ISSUE TITLE
Ajouter --export

### ISSUE THREAD

**Issue by Machou** [x0rz/tweets_analyzer#23]
Bonjour,

Peux-tu ajouter une fonction d'exportation, json, html, txt, peu importe.

Cordialement

**Comment by x0rz** [comment]
Pour exporter quoi au juste? Les tweets ou les résultats?

**Comment by Machou** [comment]
Les résultats surtout

Je souhaiterais intégrer le script à une interface web.

**Comment by ozzi-** [comment]
Utilisez -e {nom de fichier} et -j pour exporter les résultats json
