### ISSUE TITLE
Crash while converting

### ISSUE THREAD

**Issue by step7** [x0rz/tweets_analyzer#24]
After downloading user tweets, the script crashes while converting for graphs

"Daily activity distribution (per hour)
###############################################################################
[!] Error: 'ascii' codec can't encode characters in position 7-8: ordinal not in range(128)"

I tracked it down to daily and weekly distribution activity charts printing.
Both are crashing, so commenting the daily distribution activity does not work as the weekly one crashes too.

**Comment by x0rz** [comment]
Can you give me a username that will produce this result?
Thank you

**Comment by step7** [comment]
hi, anything throws this error.

@potus i.e. but also @support

**Comment by x0rz** [comment]
What's your python version and OS you're using? I can't reproduce.

**Comment by step7** [comment]
Debian 8, python version I will check later.

**Comment by step7** [comment]
python is version 2.7.9

**Comment by x0rz** [comment]
Are you sure you are running the latest version from the repository? I'm not reproducing this bug :(

**Comment by step7** [comment]
Confirmed, latest version, still buggy. I suspect some locale Mismatch??

**Comment by step7** [comment]
Ok came around the issue. I setup the locale and now works flawlessly.

Commands to set locale:
1: export LANG=en_US.UTF-8
2: dpkg-reconfigure locales
   and select the desired locale.

I think you can close it!

**Comment by x0rz** [comment]
Cool! 👍
