### ISSUE TITLE
Multiple Users analysis

### ISSUE THREAD

**Issue by antongiac** [x0rz/tweets_analyzer#36]
Hello, I was wondering whether is possible to analyse multiple users with a single run.
Thanks for the great script

**Comment by ozzi-** [comment]
Judging by the code, this is not possible.
You could use something like this:
```
for nick in "$@"
do
  echo "Tweet Analyzer running for: $nick"
  ./tweets_analyzer.py --name $nick
done
```

**Comment by x0rz** [comment]
Because of Twitter API limits (see https://developer.twitter.com/en/docs/basics/rate-limiting.html) I'd rather implement such feature at the moment
