### ISSUE TITLE
[!] Twitter error: [{u'message': u'Invalid or expired token.', u'code': 89}]

### ISSUE THREAD

**Issue by scrblrus** [x0rz/tweets_analyzer#38]
I'm not sure where this error originated from as I have not used tweets_analyzer in the past. I will say that it returns this error every time I try to run from the CLI.

**Comment by Z3r0Un1x** [comment]
Got the same error output... Might be something wrong with the Twitter API??

**Comment by Z3r0Un1x** [comment]
Did you forget to modify the 'secrets.py' ?
