### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by rahulkapoor90** [x0rz/tweets_analyzer#6]
Can this be put on a server so that i can get a GET response?

**Comment by x0rz** [comment]
Sharing an API key and using it on a public web server is probably a bad idea because of the Twitter API rate limits (see https://dev.twitter.com/rest/public/rate-limiting).
Will keep this in mind but for now closing the issue as the script is currently intended for command line.

**Comment by rahulkapoor90** [comment]
Sure. Thanks
